#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

mkdir "$install_dir/.build"
mv $install_dir/* "$install_dir/.build"
chown -R "$app:$app" "$install_dir/.build"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app... (this may take a while)"

pushd $install_dir/.build
    ynh_hide_warnings corepack enable
    ynh_exec_as_app git config --global user.name "enafore"
    ynh_exec_as_app git config --global user.email "you@example.com"
    ynh_exec_as_app git config --global init.defaultBranch master
    ynh_exec_as_app git init
    ynh_exec_as_app git add .
    ynh_exec_as_app git commit -m "init"
    ynh_hide_warnings ynh_exec_as_app pnpm install --frozen-lockfile
    ynh_hide_warnings ynh_exec_as_app pnpm build
popd

mv $install_dir/.build/__sapper__/export/* $install_dir/
ynh_safe_rm "$install_dir/.build"
ynh_safe_rm "$install_dir/.cache"
ynh_safe_rm "$install_dir/.local"
ynh_safe_rm "$install_dir/.npm"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed."
